title: Zero Day Journal
author: Musa Arslan
email: 
description: >-
  Documenting my journey from Service Desk to Cyber — notes, labs, and lessons learned.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://musa-arslan0123.github.io/zero-day-journal"
theme: minima
plugins:
  - jekyll-feed

minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/musa-arslan0123" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/musa-arslan0123" }

markdown: kramdown
kramdown:
  input: GFM

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: "Musa Arslan"
      categories: [learning]
      tags: [cyber, lab-notes]

