title: Musa’s Cyber Journey
author: Musa Arslan
email: 
description: >-
  Notes from my path from Service Desk to Cyber — labs, lessons, and mistakes I learned from.
baseurl: "" # the subpath of your site, e.g. /blog
url: ""     # the base hostname & protocol for your site
theme: minima
plugins:
  - jekyll-feed

# Minima settings
minima:
  skin: auto
  social_links:
    - { platform: github,  user_url: "https://github.com/" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/" }

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Collections and defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: "Musa Arslan"
      categories: [learning]
      tags: [cyber, lab-notes]
